### ISSUE TITLE
Add filter for the redirection after login

### ISSUE THREAD

**Issue by dasllama** [wpcodingde/User-Frontend#13]
See [this post](https://wordpress.org/support/topic/redirection-issue-6?replies=4)

**Comment by RevConcept** [comment]
So has this been fixed? Can you let us know how to setup the redirect?

**Comment by dasllama** [comment]
@RevConcept Since Version 1.0.3 you have the possibility to filter the URL. You can hook to ```uf_perform_login_redirection_url``` to change it. I hope that helps.
