### ISSUE TITLE
White screen front-end update to Version 1.0.3

### ISSUE THREAD

**Issue by danaskallman** [wpcodingde/User-Frontend#16]
Just wanted to reference this error I am getting after updating today. The error ison WP Version 4.1:

*Fatal error: Call to undefined function get_plugin_data() in /home/nycet/public_html/wp-content/plugins/user-frontend/inc/action-handler.php on line 18*

Also referencing support post on WP forum with the same error. 

https://wordpress.org/support/topic/error-after-update-35?replies=1

**Comment by dasllama** [comment]
Thanks for reporting, fixed in version 1.0.4. Release to wp.org follows now.
